version: devel-{build}

os: Visual Studio 2015

platform:
    - x64
    - x86

environment:
    matrix:
    - PYTHON: 27
    - PYTHON: 36
    - CONDA: 27
    - CONDA: 35

shallow_clone: true

install:
    - ps: |
        if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }
        if ($env:PYTHON) {
          if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
          $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
          pip install --disable-pip-version-check --user --upgrade pip setuptools
        } elseif ($env:CONDA) {
          if ($env:CONDA -eq "27") { $env:CONDA = "" }
          if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
          $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda update -q conda
          conda install -q conda-build
        }
    - if "%platform%" == "x64" SET VS_FULL=Visual Studio 14 2015 Win64
    - if "%platform%" == "x86" SET VS_FULL=Visual Studio 14 2015
    - cd ..
    - git clone -b wOnlineCI --depth=1 https://github.com/msis/core-moos
    - cd core-moos
    - mkdir build
    - cd build
    - cmake -G "%VS_FULL%" -DENABLE_EXPORT=ON -DUSE_ASYNC_COMMS=ON -DCMAKE_BUILD_TYPE=Release ../
    - cmake --build . --config Release
    - cmake --build . --config Release --target install

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - ps: |
        if ($env:PYTHON) {
          python setup.py sdist
          pip install --verbose dist\pymoos-0.0.1.tar.gz
        } else {
          conda build conda.recipe
          conda install --use-local pymoos
        }

test_script:
    - ps: |
        cd tests
        python run_close.py
        python simple_comms.py
        python register.py
        python callbacks.py
