version: devel-{build}

os: Visual Studio 2015

test: off

platform:
    - x64
    - x86

environment:
    matrix:
    - CONDA: 27
    - CONDA: 35

shallow_clone: true

install:
    - ps: |
        if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }
        if ($env:PYTHON) {
          if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
          $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
          pip install --disable-pip-version-check --user --upgrade pip wheel
          pip install pytest numpy scipy
        } elseif ($env:CONDA) {
          if ($env:CONDA -eq "27") { $env:CONDA = "" }
          if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
          $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
          conda install -y -q pytest numpy scipy
        }
    - if "%platform%" == "x64" SET VS_FULL=Visual Studio 14 2015 Win64
    - if "%platform%" == "x86" SET VS_FULL=Visual Studio 14 2015
    - cd ..
    - git clone -b wOnlineCI --depth=1 https://github.com/msis/core-moos
    - cd core-moos
    - mkdir build
    - cd build
    - cmake -G "%VS_FULL%" -DENABLE_EXPORT=ON -DUSE_ASYNC_COMMS=ON -DTIME_WARP_AGGLOMERATION=0.4 -DCMAKE_BUILD_TYPE=Release ../
    - cmake --build . --config Release
    - cmake --build . --config Release --target install

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - mkdir build
    - cd build
    - cmake -G "%VS_FULL%"
    - cmake --build . --config Release

on_success:
    - cmake --build . --config Release --target install
