language: cpp

sudo: required

os:
    - linux
    - osx

compiler:
    - gcc

env:
    - BUILD_TYPE=Release

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kubuntu-backports
        packages:
            - g++-4.8
            - cmake

before_script:
    - if [ "`uname`" != "Darwin" ] ; then export MOOS_CXX_FLAGS="-fPIC -Wno-long-long"; fi
    - if [ "`uname`" != "Darwin" ] ; then export CXX="g++-4.8"; fi
    - cd ..
    - git clone -b wOnlineCI --depth=1 https://github.com/msis/core-moos
    - cd core-moos
    - mkdir build
    - cd build
    - cmake -DENABLE_EXPORT=ON -DUSE_ASYNC_COMMS=ON -DTIME_WARP_AGGLOMERATION=0.4 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=$MOOS_CXX_FLAGS ..
    - cmake --build . --config Release
    - sudo cmake --build . --config Release --target install
    - cd $TRAVIS_BUILD_DIR
    - mkdir build/

script:
    - cd build/
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=$MOOS_CXX_FLAGS ../
    - cmake --build . --config Release

after_script:
    - sudo cmake --build . --config Release --target install
